---
- name: variable test
  hosts: localhost

  vars:
    var_one: computers
    var_two: i Hate
    var_three: "{{ var_two }} {{ var_one }}"
  
  tasks:
  - name: print out var_three
    debug:
      msg: "{{var_three}}"
